'use client'

import React, { useEffect, useState } from 'react'
import { getAiIllustration } from '@/app/services/ChatGPTService'
import styles from './components.module.css'
import Image from 'next/image'
import Button from '../Story/Button/Button'
import { LoadingMessages } from '@/app/utils/constants'

function Illustration () {
  const [imgSrc, setImgSrc] = useState('')
  const [loading, setLoading] = useState<boolean>(false)
  const [messageIndex, setMessageIndex] = useState<number>(0)
  const [message, setMessage] = useState<string>()

  function handleClickIllustrate () {
    setLoading(true)
    const inputElem = document?.querySelector('#inputAbout') as HTMLInputElement
    const about = inputElem.value

    // Uses the service to obtain a Promise with the API response.
    getAiIllustration(about).then(
      (res) => {
        setImgSrc(`data:image/jpeg;base64,${res.data[0].b64_json}`)
        setLoading(false)
      },
      (err) => {
        console.log('e', err)
        setLoading(false)
      }
    )
  }

  // Change message on loading times
  useEffect(() => {
    let timer

    if (loading) {
      setMessage(LoadingMessages[messageIndex])

      timer = setTimeout(() => {
        if (messageIndex < LoadingMessages.length - 1) {
          setMessageIndex(messageIndex + 1)
          setMessage(LoadingMessages[messageIndex + 1])
        }
      }, 5000)
    } else {
      setMessageIndex(0)
      clearTimeout(timer)
    }
  }, [loading, messageIndex])

  return (
    <div className={styles.main}>
      <div className={styles.row}>
        Get a Illustration about...
      </div>

      <div className={styles.row}>
        <input id='inputAbout' name='inputAbout' type='text' placeholder='a dog with a sword' className={styles.input} />
        <Button enabled={!loading} onClick={handleClickIllustrate} buttonText='Illustrate' />
      </div>

      <div className={styles.row}>
        {loading && <p>{message}</p>}

        {imgSrc &&
          <Image
            src={imgSrc}
            alt='an image generated by AI'
            width={512}
            height={512}
          />}
      </div>
    </div>
  )
}

export default Illustration
