const Disclaimer = () => {
  return (
    <div style={{ maxWidth: '800px', margin: '0px auto' }}>
      <h2>Disclaimer:</h2>
      <br />
      <p>
        Welcome to our website, which is developed with an aim to provide a creative and fun storytelling experience for children. We use cutting-edge artificial intelligence (AI) technologies to generate stories that are both entertaining and educational. The stories, along with the images, are created using AI algorithms and may not be entirely accurate or free from errors.
      </p>
      <br />
      <p>
        It is important to note that the content of the stories and images generated by AI may not be suitable for all ages, and we advise parental guidance for children under 13 years old. The content may also contain themes or references that some users may find offensive or objectionable.
        We do not guarantee the accuracy or completeness of the information presented in the stories and images generated by AI, and we shall not be held responsible for any damages or losses incurred as a result of using our website or its content.
      </p>
      <br />
      <p>
        We also would like to inform our users that the use of our website and its content is at their own risk. We do not provide any warranty or representation, express or implied, regarding the accuracy, reliability, or completeness of the content provided on our website.
        We reserve the right to modify or terminate our website or its content at any time without prior notice. We may also modify these terms and conditions at any time, and the continued use of our website constitutes acceptance of any changes made.
      </p>
      <br />
      <p>
        By using our website, you acknowledge and agree to these terms and conditions, and you agree to indemnify us and hold us harmless from any claims or damages arising out of your use of our website or its content.
      </p>
    </div>
  )
}

export default Disclaimer
